### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "android.view.vector"

### ISSUE THREAD

**Issue by MiracleMiracle** [telly/MrVector#12]
I put this stuff in my build-file
dependencies {
    compile 'com.telly:mrvector:0.2.0'
}

Gradle seems to be able to find it, since no errors are thrown after sync ( using android studio ).

But when I create this layout ( named svg_test.xml )

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    >

    <vector
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:tools="http://schemas.android.com/tools"
        xmlns:auto="http://schemas.android.com/apk/res-auto"

        tools:targetApi="21"

        auto:width="@dimen/simple_vector_width"
        auto:height="@dimen/simple_vector_height"
        auto:viewportWidth="@integer/simple_vector_viewport_width"
        auto:viewportHeight="@integer/simple_vector_viewport_height"

        android:width="@dimen/simple_vector_width"
        android:height="@dimen/simple_vector_height"
        android:viewportWidth="@integer/simple_vector_viewport_width"
        android:viewportHeight="@integer/simple_vector_viewport_height">

        <path
            auto:strokeColor="#FF000000"
            auto:strokeWidth="@dimen/simple_stroke_width"
            auto:pathData="@drawable/earth16"

            android:strokeColor="#FF000000"
            android:strokeWidth="@dimen/simple_stroke_width"
            android:pathData="@drawable/earth16" />

    </vector>
</LinearLayout>

and this activity

public class SVGActivityTest extends Activity
{
  @Override
  protected void onCreate(Bundle savedInstanceState)
  {

    super.onCreate(savedInstanceState);
    setContentView(R.layout.svg_test);
  }
}

And start it, it crashes with:

java.lang.RuntimeException: Unable to start activity
.
.
.
Caused by: android.view.InflateException: Binary XML file line #10: Error inflating class vector
.
.
.
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.vector" on path: <snip>

Using android 4.3

Do I have to add something else?

**Comment by eveliotc** [comment]
Your layout appears to be incomplete, anyway as stated in README.md, layout inflation (e.g. referencing `@drawable/vectordrawable.xml` in XML layouts) is work in progress and is not ready for use yet, you have to use `MrVector.inflate` from Java for now.
