### ISSUE TITLE
Drawable tinting

### ISSUE THREAD

**Issue by rekire** [telly/MrVector#9]
Because you like to add this feature, I did something already for a custom control: https://github.com/rekire/TintedDrawable

Hopfully this will help you.

**Comment by eveliotc** [comment]
Thanks @rekire, tinting is already implemented but only works from code not from xml that's what needs to get fixed :)

**Comment by pjwelcome** [comment]
Hi there. could you please provide an example of tinting as the built in tint function works on drawables but its only for 21 and up.

Thank you

**Comment by ozodrukh** [comment]
did you try using `setColorFilter(ColorFilter filter)`?

**Comment by rekire** [comment]
@pjwelcome my small library just works by code. Since I use it for a custom control this is no issue. On the link above is a small example in the readme.md

**Comment by pjwelcome** [comment]
I did try setColorFilter but it seems to blend the tint color and the background color together. having the tint is not something major just thought it would be nice. 

Thanks guys for the responses.
